### ISSUE TITLE
IseClient timeout with leaked warning

### ISSUE THREAD

**Issue by Jenfong** [iFLYTEK-OP/websdk-java#66]
sdk version:
websdk-java-speech-2.0.3.jar

log:
十二月 04, 2024 9:06:34 上午 okhttp3.internal.platform.Platform log
警告: A connection to https://ise-api.xfyun.cn/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by abelzha** [comment]
邮件已收到！

**Comment by Jenfong** [comment]
# with ise sdk error，append log:
`警告: A connection to https://ise-api.xfyun.cn/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:144)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
	at okhttp3.RealCall.enqueue(RealCall.java:98)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:183)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:436)
	at cn.xfyun.base.webscoke`

# with IseDemo 
> https://xfyun-doc.xfyun.cn/1603684292532483/ise_ws_java_demo.zip
  - with the same appId/apiKey/apiSecret  and the same text and audio file is work correct!
   `sid:ise000e921c@dx1938ff528aa6f21812`

**Comment by Dzy-1026** [comment]
remember to close the **response** when there is a WebSocket error or in the onOpen callback.
        if (response != null) {
            // Close the handshake Response to avoid connection leakage
            response.close();
        }
